create table permission
(
    id              bigint auto_increment
        primary key,
    actions         varchar(255) not null,
    permission_id   varchar(255) not null,
    permission_name varchar(255) not null,
    role_id         varchar(255) not null
)
    engine = MyISAM;

INSERT INTO tntt.permission (id, actions, permission_id, permission_name, role_id) VALUES (1, '[{"action":"add","defaultCheck":false,"describe":"新增"},{"action":"query","defaultCheck":false,"describe":"查询"},{"action":"get","defaultCheck":false,"describe":"详情"},{"action":"update","defaultCheck":false,"describe":"修改"},{"action":"delete","defaultCheck"', 'dashboard', 'dashboard', 'admin');
INSERT INTO tntt.permission (id, actions, permission_id, permission_name, role_id) VALUES (2, '[{"action":"add","defaultCheck":false,"describe":"新增"},{"action":"query","defaultCheck":false,"describe":"查询"},{"action":"get","defaultCheck":false,"describe":"详情"},{"action":"update","defaultCheck":false,"describe":"修改"},{"action":"delete","defaultCheck"', 'exception', 'exception', 'admin');
INSERT INTO tntt.permission (id, actions, permission_id, permission_name, role_id) VALUES (3, '[{"action":"add","defaultCheck":false,"describe":"新增"},{"action":"query","defaultCheck":false,"describe":"查询"},{"action":"get","defaultCheck":false,"describe":"详情"},{"action":"update","defaultCheck":false,"describe":"修改"},{"action":"delete","defaultCheck"', 'result', 'result', 'admin');
INSERT INTO tntt.permission (id, actions, permission_id, permission_name, role_id) VALUES (4, '[{"action":"add","defaultCheck":false,"describe":"新增"},{"action":"query","defaultCheck":false,"describe":"查询"},{"action":"get","defaultCheck":false,"describe":"详情"},{"action":"update","defaultCheck":false,"describe":"修改"},{"action":"delete","defaultCheck"', 'profile', 'profile', 'admin');
INSERT INTO tntt.permission (id, actions, permission_id, permission_name, role_id) VALUES (5, '[{"action":"add","defaultCheck":false,"describe":"新增"},{"action":"import","defaultCheck":false,"describe":"导入"},{"action":"get","defaultCheck":false,"describe":"详情"},{"action":"update","defaultCheck":false,"describe":"修改"}]', 'table', 'table', 'admin');
INSERT INTO tntt.permission (id, actions, permission_id, permission_name, role_id) VALUES (6, '[{"action":"add","defaultCheck":false,"describe":"新增"},{"action":"get","defaultCheck":false,"describe":"详情"},{"action":"query","defaultCheck":false,"describe":"查询"},{"action":"update","defaultCheck":false,"describe":"修改"},{"action":"delete","defaultCheck"', 'form', 'form', 'admin');
INSERT INTO tntt.permission (id, actions, permission_id, permission_name, role_id) VALUES (7, '[{"action":"add","defaultCheck":false,"describe":"新增"},{"action":"query","defaultCheck":false,"describe":"查询"},{"action":"get","defaultCheck":false,"describe":"详情"},{"action":"update","defaultCheck":false,"describe":"修改"},{"action":"delete","defaultCheck"', 'order', 'order', 'admin');
INSERT INTO tntt.permission (id, actions, permission_id, permission_name, role_id) VALUES (8, '[{"action":"add","defaultCheck":false,"describe":"新增"},{"action":"get","defaultCheck":false,"describe":"详情"},{"action":"update","defaultCheck":false,"describe":"修改"},{"action":"delete","defaultCheck":false,"describe":"删除"}]', 'permission', 'permission', 'admin');
INSERT INTO tntt.permission (id, actions, permission_id, permission_name, role_id) VALUES (9, '[{"action":"add","defaultCheck":false,"describe":"新增"},{"action":"get","defaultCheck":false,"describe":"详情"},{"action":"update","defaultCheck":false,"describe":"修改"},{"action":"delete","defaultCheck":false,"describe":"删除"}]', 'role', 'role', 'admin');
INSERT INTO tntt.permission (id, actions, permission_id, permission_name, role_id) VALUES (10, '[{"action":"add","defaultCheck":false,"describe":"新增"},{"action":"get","defaultCheck":false,"describe":"详情"},{"action":"query","defaultCheck":false,"describe":"查询"},{"action":"update","defaultCheck":false,"describe":"修改"},{"action":"delete","defaultCheck"', 'table', 'table', 'admin');
INSERT INTO tntt.permission (id, actions, permission_id, permission_name, role_id) VALUES (11, '[{"action":"add","defaultCheck":false,"describe":"新增"},{"action":"import","defaultCheck":false,"describe":"导入"},{"action":"get","defaultCheck":false,"describe":"详情"},{"action":"update","defaultCheck":false,"describe":"修改"},{"action":"delete","defaultCheck', 'user', 'user', 'admin');
INSERT INTO tntt.permission (id, actions, permission_id, permission_name, role_id) VALUES (12, '[{"action":"add","defaultCheck":false,"describe":"新增"},{"action":"import","defaultCheck":false,"describe":"导入"},{"action":"get","defaultCheck":false,"describe":"详情"},{"action":"update","defaultCheck":false,"describe":"修改"},{"action":"delete","defaultCheck', 'support', 'support', 'admin');
